### ISSUE TITLE
ProcessException: fatal: Needed a single revision

### ISSUE THREAD

**Issue by fobf** [kevmoo/peanut.dart#125]
lutter pub global run peanut
`ProcessException: fatal: Needed a single revision
  Command: git rev-parse --verify --symbolic-full-name HEAD
#0      _throwIfProcessFailed (package:git/src/top_level.dart:39:5)
#1      runGit (package:git/src/top_level.dart:17:5)
<asynchronous suspension>
<asynchronous suspension>
#3      run (package:peanut/src/peanut.dart:37:25)
<asynchronous suspension>
#4      main (file:///D:/dev/flutter/.pub-cache/hosted/pub.dartlang.org/peanut-4.1.1/bin/peanut.dart:55:5)
<asynchronous suspension>`

**Comment by kevmoo** [comment]
Ooo! This is a fun one.

You might need to set HEAD locally. See https://stackoverflow.com/a/8840516/39827

`git remote set-head origin some_branch`

At the same time, I should handle this better. Could also be a windows thing. 🤔

**Comment by fobf** [comment]
Sorry, I'm confused what should I write for  some_branch  ?
I think I had an error when I accidentally made a commit to push to flutter
repo but I reset it.
Still, this error somehow affects me.

пн, 31 янв. 2022 г. в 23:18, Kevin Moore ***@***.***>:

**Comment by kevmoo** [comment]
likely `master` or `main`

**Comment by fobf** [comment]
Wow , thanks  'main' worked for me

**Comment by kevmoo** [comment]
Need to fix that, though!
