### ISSUE TITLE
Flutter SDK not detected when using Puro

### ISSUE THREAD

**Issue by azliR** [kevmoo/peanut.dart#150]
It seems, the Flutter SDK is not detected when installed with [Puro](https://puro.dev/). It's not running `flutter build`, but `dart run build_runner`. I got this log
```
❯ flutter pub global run peanut --extra-args="--target lib/main_production.dart" --verbose
[  +73 ms] executing: uname -m
[  +29 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/azlir/.puro/envs/stable/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] executing: [/home/azlir/.puro/envs/stable/flutter/] git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[  +29 ms] Exit code 0 from: git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] 3.7.7
[  +43 ms] executing: [/home/azlir/.puro/envs/stable/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/azlir/.puro/envs/stable/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +28 ms] executing: [/home/azlir/.puro/envs/stable/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +40 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +77 ms] executing: /home/azlir/.puro/envs/stable/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color global run peanut
--extra-args=--target lib/main_production.dart --verbose
Validating packages:
  /home/azlir/Documents/flutter_murojaah_web

Package:     /home/azlir/Documents/flutter_murojaah_web
Directories: web
Command:     dart run build_runner build --release \
               --target lib/main_production.dart \
               --output web:/tmp/peanut.1679098253679.UVIACZ

Could not find an option named "target".

Usage: build_runner build [arguments] [directories]
-h, --help                          Print this usage information.
-d, --delete-conflicting-outputs    By default, the user will be prompted to
                                    delete any files which already exist but
                                    were not known to be generated by this
                                    specific build script.
                                    
                                    Enabling this option skips the prompt and
                                    deletes the files. This should typically be
                                    used in continues integration servers and
                                    tests, but not otherwise.
    --low-resources-mode            Reduce the amount of memory consumed by the
                                    build process. This will slow down builds
                                    but allow them to progress in resource
                                    constrained environments.
-c, --config                        Read `build.<name>.yaml` instead of the
                                    default `build.yaml`
    --[no-]track-performance        Enables performance tracking and the /$perf
                                    page.
    --log-performance               A directory to write performance logs to,
                                    must be in the current package. Implies
                                    `--track-performance`.
-o, --output                        A directory to copy the fully built package
                                    to. Or a mapping from a top-level directory
                                    in the package to the directory to write a
                                    filtered build output to. For example
                                    "web:deploy".
-v, --verbose                       Enables verbose logging.
-r, --[no-]release                  Build with release mode defaults for
                                    builders.
    --define                        Sets the global `options` config for a
                                    builder by key.
    --[no-]symlink                  Symlink files in the output directories,
                                    instead of copying.
    --build-filter                  An explicit filter of files to build.
                                    Relative paths and `package:` uris are
                                    supported, including glob syntax for paths
                                    portions (but not package names).
                                    
                                    If multiple filters are applied then outputs
                                    matching any filter will be built (they do
                                    not need to match all filters).
    --enable-experiment             A list of dart language experiments to
                                    enable.

Run "build_runner help" to see global options.
Error running "/home/azlir/.puro/shared/caches/1837b5be5f0f1376a1ccf383950e83a80177fb4e/dart-sdk/bin/dart run build_runner build --release --target lib/main_production.dart --output web:/tmp/peanut.1679098253679.UVIACZ"
Exit code 64
[+2107 ms] "flutter global" took 2,272ms.
[   +5 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:586:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:250:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +188 ms] ensureAnalyticsSent: 186ms
[   +1 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
I forked it and somehow fixed it by changing the `Platform.resolvedExecutable` to `Platform.executable`. You can see it [here](https://github.com/azliR/peanut.dart). But I really don't know if it will break with other installations, including normal a installation.

**Comment by kevmoo** [comment]
There is other work I need to investigate here. I think there may be environment vars involved that could help...

**Comment by rodydavis** [comment]
I was getting the opposite problem when compiling a dart web project but detected flutter (even though there was not a flutter import).
