### ISSUE TITLE
error on windows: 'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kasperpeulen** [kevmoo/peanut.dart#3]
Seems to be something with git ? I installed git using chocolatey, maybe that is the problem ?

```
Took 0:00:19.352121 to compile dartnow|web/main.dart.
Built 799 files to "C:\Users\KASPE_~1\AppData\Local\Temp\peanut.1438531310721.c87eb0af-392f-11e5-82ce-08002700a877".
ProcessException: stdout:

stderr:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

  Command: C:\Program Files (x86)\Git\cmd\git.EXE --work-tree=C:\Users\KASPE_~1\AppData\Local\Temp\peanut.1438531310721.c87eb0af-392f-11e5-82ce-08002700a877\web co
mmit --verbose -m Built web
#0      _throwIfProcessFailed (package:git/src/top_level.dart:44)
#1      runGit.<runGit_async_body> (package:git/src/top_level.dart:29)
#2      _RootZone.runUnary (dart:async/zone.dart:1166)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#5      _Future._completeWithValue (dart:async/future_impl.dart:368)
#6      Future.wait.<anonymous closure> (dart:async/future.dart:299)
#7      _RootZone.runUnary (dart:async/zone.dart:1166)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#10     _Future._completeWithValue (dart:async/future_impl.dart:368)
#11     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#13     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by kevmoo** [comment]
Assuming stale. Please reopen with recent SDK + stacktrace.
