### ISSUE TITLE
I'm facing this error while run peanut command

### ISSUE THREAD

**Issue by Rakshak1344** [kevmoo/peanut.dart#72]
please help me with this problem.

```
$ flutter pub global run peanut
Validating packages:
  D:\My Files\flutter-apps\flutter_web\profile
Package:     D:\My Files\flutter-apps\flutter_web\profile
Directories: web
Command:     flutter build web

Deleting build...
                   1,413ms
Deleting .dart_tool...
                   1,136ms
Compiling lib\main.dart for the Web...        
                     33.5s
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2727:7)
#1      new Directory.fromUri (dart:io/directory.dart:152:59)
#2      copyFilesRecursive (package:peanut/src/flutter.dart:59:29)
<asynchronous suspension>
#3      runFlutterBuild (package:peanut/src/flutter.dart:44:9)
<asynchronous suspension>
#4      run (package:peanut/src/peanut.dart:123:15)
<asynchronous suspension>
#5      main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/peanut-3.4.2/bin/peanut.dart:54:11)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by kevmoo** [comment]
This looks like something specific to Flutter + Windows support.

Hrm...i'll have to dig in...

**Comment by Rakshak1344** [comment]
I am confused about the error, is it a problem with the code or peanut?

**Comment by kevmoo** [comment]
It's peanut I'm almost certain...

**Comment by Rakshak1344** [comment]
Any other way to host?

**Comment by kevmoo** [comment]
Are you on Gitter?

Can you start a chat with me there? Find me in https://gitter.im/dart-lang/TALK-general

**Comment by kevmoo** [comment]
> Any other way to host?

You don't *have* to use peanut, but it does make it easier...
